# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostelOwner',
            fields=[
                ('idno', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('email', models.CharField(max_length=32, null=True, unique=True)),
            ],
        ),
    ]
