# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        ('hostelmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelDetails',
            fields=[
                ('hostel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hostel_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('rooms', models.IntegerField()),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Client')),
            ],
        ),
    ]
