# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanager', '0002_hosteldetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostelDetails',
            new_name='Hostel',
        ),
    ]
