# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelmanager', '0003_auto_20170624_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=2500, max_digits=7),
        ),
        migrations.AlterField(
            model_name='hostelowner',
            name='idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
